# kind-config.yaml
kind: Cluster
name: demo-cluster  #생성되는 클러스터의 이름 
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080 # 생성된 Pod의 Service Controller 포트
        hostPort: 8080 # 외부에서 요청하는 포트 localhost:8080 -> 30080 -> 80 -> nginx 로 포트포워딩
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
