apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: NodePort # 내부는 30080로 들어 온 포트를 내부의 pod의 80에 연결하는 포트
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
