#Kind 클러스터 정의
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

#클러스터에 포함될 노드를 정의
nodes:
  #control-plane 역할을 하는 node 1개 생성
- role: control-plane

  #외부에서 도커 컨테이너(즉, 클러스터 내부 Pod)에 접근 할 수 있도록 포트 매핑 설정
  extraPortMappings:
    #일반 웹 접근용 포트 매칭(옵션)
  - containerPort: 80
    hostPort: 80 
    protocol: TCP

  - containerPort: 443
    hostPort: 443
    protocol: TCP  

    #SpringBoot API 서비스용 포트 매핑
  - containerPort: 30090
    hostPort: 18080 
    protocol: TCP  

    #Next.js UI 프론트엔드용 매핑
  - containerPort: 30080
    hostPort: 30080 
    protocol: TCP   